# Homework 03: Python Fundamentals

This notebook demonstrates NumPy operations, pandas data inspection,
summary statistics, groupby aggregation, and reusable functions.

In [1]:
import numpy as np
import pandas as pd

In [ ]:
## Numpy operations
values = np.array([1, 2, 3, 4, 5])

print("Original array:", values)
print("Add 10:", values + 10)
print("Multiply by 2:", values * 2)
print("Squared:", values ** 2)

Original array: [1 2 3 4 5]
Add 10: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Squared: [ 1  4  9 16 25]

In [4]:
## read csv
df = pd.read_csv("data/raw/starter_data.csv")

df.head()

  category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  10 non-null     object
 1   value     10 non-null     int64
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [13]:
print(df.columns.tolist())

['category', 'value', 'date']

In [8]:
## summary statistics
summary = df.describe()

summary

           value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

In [15]:
## reusable function
def get_summary_stats(data):
    return data.describe()

summary = get_summary_stats(df)

summary

           value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

In [10]:
## groupby
grouped_summary = df.groupby("category").mean(
    numeric_only=True
)

grouped_summary

              value
category
A         11.500000
B         15.666667
C         27.666667

In [11]:
from pathlib import Path

processed_dir = Path("data/processed")
processed_dir.mkdir(parents=True, exist_ok=True)

summary_file = processed_dir / "summary.csv"
summary.to_csv(summary_file)

print("Summary saved to:", summary_file)
print("File exists:", summary_file.exists())

Summary saved to: data/processed/summary.csv
File exists: True